version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: OrderDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql